name: "Telegraf Addon"
description: "Influxdata telegraf addon - infradom"
version: "1.33.103"
slug: "telegraf_addon_infradom"
url: "https://github.com/infradom/telegraf-addon-infradom"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
boot: manual
#hassio_api: true
#hassio_role: "admin"
#auth_api: true
#docker_api: true
#host_network: true
#apparmor: false
maps:
  - config: "rw"
    ssl: "rw"
    addons: "rw"
    backup: "rw"
    share: "rw"
ports:
  8086/tcp: 8086

privileged: [SYS_ADMIN]
options:
  loglevel: "info"
  tcpport: !!int 8086
  custom_conf: 
      enabled: false
      location: "/telegraf-custom.conf"
  hostname: "ha-telegraf-addon"
  skip_processors_after_aggregators: false
  influxDBv2:
      enabled: true
      url: "https://eu-central-1-1.aws.cloud2.influxdata.com"
      organization: "home"
      token: ""
      bucket: "home_assistant"
schema:
  loglevel: "list(error|warning|info|debug)"
  tcpport: "int"
  custom_conf:
      enabled: "bool"
      location: "str"
  hostname: "str"
  skip_processors_after_aggregators: "bool"
  influxDBv2:
      enabled: bool
      url: "str"
      organization: "str"
      token: "str"
      bucket: str

