name: "Telegraf Addon"
description: "Influxdata telegraf addon - infradom"
version: "1.33"
slug: "telegraf_addon_infradom"
url: "https://github.com/infradom/telegraf-addon-infradom"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  8094/tcp: 8094

privileged: [SYS_ADMIN]
options:
  loglevel: "info"
  info_log: "write"
  tcpport: 8094
  custom_conf: 
    enabled: false
    location: "/share/telegraf.conf"
  hostname: "ha-telegraf-addon"
  influxDBv2:
    enabled: true
    url: "https://eu-central-1-1.aws.cloud.infradata.com"
    organization: "home"
    token: ""
    bucket: "home_assistant" 


  #pubkey: "ssh-rsa ReplaceByYourPublicKey modbusspy"
schema:
  loglevel: "list(error|warning|info|debug)"
  info_log: "list(read|write|both|none)"
  tcpport : "int"
  custom_conf:
    enabled: "bool"
    location: "str"
  hostname: "str"
  influxDBv2:
    enabled: bool
    url: "str"
    organization: "str"
    token: "str"
    bucket: str

